### ISSUE TITLE
Ability to remove admin

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/infrarays-api#11]
Please I have cluttered things up while testing. If a superadmin could remove regular admins that would be great.

**Comment by kelszo** [comment]
Will fix a `DELETE /admin/:userID` route. Will return 204 on success.

**Comment by kelszo** [comment]
Actually, doesn't `DELETE /user/:userID` work? @Nautman

**Comment by Nautman** [comment]
It works!
