### ISSUE TITLE
Fields for grading should be constant

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/infrarays-api#12]
In the `application/@me/file` route the values are `CV` `GRADES` `ESSAY` `COVER_LETTER` etc. In the `application/:userId/grade` the values are `cv` `grades` `essays` `recommendations` etc. They should be the same in my opinion.

**Comment by kelszo** [comment]
The reason for this is that they are actually two different things. The file route refers file types and are thus constants. The grading routes refers to columns in the database and thus follow a camelCase notation (that is translated to snake_case for SQL naming convention sake). 

This might change in the future if we intend to generalise the API to allow for more generic grades. Then the values in the route would be considered as constants and thus follow a CONSTANT_CASE naming convention and refer to a grade type and not column in the database. 

Though, personally I find it weird to have a CONSTANT_CASED key in an JSON object.
