### ISSUE TITLE
Max length is incorrect

### ISSUE THREAD

**Issue by Nautman** [digitalungdom-se/infrarays-api#17]
The max length is not 8192, it is actually 255.

https://github.com/digitalungdom-se/infrarays-api/blob/b0a647f96c916eb08a4a1ef7473df89c0d76ff88/src/api/validators/admin.ts#L73

**Comment by kelszo** [comment]
This error does not exist in prod. It was caused by an incorrect DB migration and was solved on the prod server by correctly migrating the DB before the application started but never in staging.
